server:
  port: 8088
spring:
  application:
    # 应用的名称，选择性配置
    name: tokenDemo    #项目名和nacos的dataId相匹配
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123mysql


mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    # 把SQL的查询的过程输出到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
upload:
  hostname: 12.152.22.30
  username: admin
  password: 123
  targetPath: aa

filePath: D:/springboot_save_file/

mail:
    user: 1942107003@qq.com
    password: ofciofkffjpvbhjj



